[package]
name = "chat-gemini"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "gmn"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
gemini-rust = "1.5.1"
url = "2.5"
argh = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
display-error-chain = "0.1.0"
futures = "0.3"
reqwest = { version = "0.12", features = ["rustls-tls"] }
anstream = "0.6"
anstyle = "1.0"
